language: cpp

#os: linux
#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - g++-7

sudo: required
dist: bionic

services:
  - docker

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-7
      env: MATRIX_EVAL="COMPILER=g++-7 && CXX=g++-7 && CC=gcc-7"

    - os: linux
      addons:
        apt:
          packages:
            - clang-8.0
      env: MATRIX_EVAL="COMPILER=clang-8.0 && CXX=clang-8.0 && CC=clang-8.0"

before_install:
  - eval "${MATRIX_EVAL}"
  - if [[ ${TRAVIS_EVENT_TYPE} == cron && ${COMPILER} == g++* ]]; then
        export CRON_GCC_BUILD=true;
        export COVERITY_DESC=`date`;
        export COVERITY_REPO=`echo ${TRAVIS_REPO_SLUG} | sed 's/\//\%2F/g'`;
    else
        export CRON_GCC_BUILD=false;
    fi
  - if [[ "${CRON_GCC_BUILD}" == true ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker run -itd --name pandora -v `pwd`:/pandora/package -e "COMPILER=$COMPILER" -e "CODECOV_TOKEN=$CODECOV_TOKEN" pandorapfa/pandorapfa_data:latest /bin/bash;
    else
      docker run -itd --name pandora -v `pwd`:/pandora/package -e "COMPILER=$COMPILER" pandorapfa/pandorapfa_c17:latest /bin/bash;
    fi

install:
  - if [[ "${CRON_GCC_BUILD}" == true ]]; then
        echo "Downloading Coverity Scan tool...";
        wget https://scan.coverity.com/download/linux64 --post-data "token=${COVERITY_SCAN_TOKEN}&project=${COVERITY_REPO}" --no-check-certificate -O ./coverity_tool.tgz; mkdir cov-analysis-linux64; tar -xf coverity_tool.tgz -C cov-analysis-linux64 --strip-components=1 > /dev/null 2>&1;
    fi
  - docker exec -it pandora /bin/bash -c "source pull_pandora_pfa.sh"
  - docker exec -it pandora /bin/bash -c "source install_pandora_sdk.sh"
  - docker exec -it pandora /bin/bash -c "source install_pandora_monitoring.sh"

script:
  - ${CC} --version
  - ${CXX} --version
  - cmake --version
  - if [[ "${CRON_GCC_BUILD}" == true ]]; then
        docker exec -it pandora /bin/bash -c "cd /pandora/package && source /pandora/build_larcontent.sh coverity";
        curl --form token=${COVERITY_SCAN_TOKEN} --form email=${COVERITY_TARGET_EMAIL} --form file=@build/coverity_build.tgz --form version="master" --form description="${COVERITY_DESC}" https://scan.coverity.com/builds?project=${COVERITY_REPO};
        docker exec -it pandora /bin/bash -c "cd /pandora/package && rm -rf build && source /pandora/build_larcontent.sh coverage";
        docker exec -it pandora /bin/bash -c "ln -s /pandora/package /pandora/LArContent && source /pandora/install_larreco.sh coverage";
        docker exec -it pandora /bin/bash -c "cd /pandora/LArContent/build && source /pandora/run_tests.sh && source /pandora/upload_codecov_report.sh";
    elif [[ "${TRAVIS_EVENT_TYPE}" == "cron" ]]; then
        echo "Coverity does not use this build";
    else
        docker exec -it pandora /bin/bash -c "cd /pandora/package && source /pandora/build_larcontent.sh";
    fi

notifications:
  email:
    on_success: never
    on_failure: always
